# Generated by Django 4.2.2 on 2023-06-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the class(e.g.,"Grade 10")')),
                ('section', models.CharField(max_length=100, verbose_name='section of the class(e.g.,"A", "B")')),
                ('start_time', models.TimeField(verbose_name='start time of the class')),
                ('end_time', models.TimeField(verbose_name='end time of the class')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the exam')),
                ('date', models.DateField(verbose_name='date of the exam')),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title of the book')),
                ('author', models.CharField(max_length=100, verbose_name='author of the book')),
                ('publication_date', models.DateField(verbose_name=' publication date of the book')),
                ('availability_status', models.BooleanField(verbose_name='availability status of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title of the notice')),
                ('description', models.TextField(verbose_name='description/details of the notice')),
                ('date', models.DateField(verbose_name='date on which the notice is posted')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the subject')),
                ('code', models.CharField(max_length=10, verbose_name='unique code for the subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the teacher')),
                ('date_of_birth', models.DateField(verbose_name='birthdate of the teacher')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=10, verbose_name='gender of the teacher')),
                ('address', models.TextField(verbose_name='address of the teacher')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address of the teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the student')),
                ('roll_number', models.CharField(max_length=10, unique=True, verbose_name='roll of the student')),
                ('date_of_birth', models.DateField(verbose_name='birthdate of the student')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=10, verbose_name='gender of the student')),
                ('address', models.TextField(verbose_name='the address of the student')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address of the student')),
                ('_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(verbose_name='marks obtained by the student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date for whitch the attendance is recorded')),
                ('status', models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent')], max_length=10, verbose_name='attendance status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title of the assignment')),
                ('description', models.TextField(verbose_name='description/instructions for the assignment')),
                ('due_date', models.DateField(verbose_name='due date for the assignment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
